name: Windows Build Only
on:
  push:
    branches: [ main, master ]

jobs:
  build-windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.5.3'
          arch: 'win64_msvc2019_64'
          modules: 'qtopenglwidgets qtsql'
          # Disabling host/target might help avoid some logic branches in the action
          # that are failing due to python environment issues.
          setup-python: 'true' 

      - name: Configure CMake
        run: cmake -B build -S horos_win -G "Visual Studio 17 2022" -A x64

      - name: Build
        run: cmake --build build --config Release

      - name: Create Installer
        run: |
          cd build
          cpack -G NSIS

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: HorosWin-Installer
          path: build/*.exe
